environment:
  BOOST_ROOT: c:/Libraries/boost
  BOOST_LIBRARYDIR: c:/Libraries/boost/lib64-msvc-12.0

image: Visual Studio 2013

platform: x64

configuration:
  - Release
  - Debug

install:
  # by default, all script lines are interpreted as batch

build:
  project: c:\projects\maeparser\build\INSTALL.vcxproj
  parallel: true

before_build:
  - cd c:\projects\maeparser
  - mkdir c:\projects\maeparser\build
  - cd c:\projects\maeparser\build
  - cmake -G "Visual Studio 12 Win64" -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" -DCMAKE_INSTALL_PREFIX=%P% ..

test_script:
  - mkdir c:\projects\maeparser\build
  - ctest

